// Autogenerated from Pigeon (v8.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif



private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol StarknetInterface {
  func storePrivateKey(privateKey: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getPrivateKey(completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class StarknetInterfaceSetup {
  /// The codec used by StarknetInterface.
  /// Sets up an instance of `StarknetInterface` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: StarknetInterface?) {
    let storePrivateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.StarknetInterface.storePrivateKey", binaryMessenger: binaryMessenger)
    if let api = api {
      storePrivateKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let privateKeyArg = args[0] as! String
        api.storePrivateKey(privateKey: privateKeyArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      storePrivateKeyChannel.setMessageHandler(nil)
    }
    let getPrivateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.StarknetInterface.getPrivateKey", binaryMessenger: binaryMessenger)
    if let api = api {
      getPrivateKeyChannel.setMessageHandler { _, reply in
        api.getPrivateKey() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getPrivateKeyChannel.setMessageHandler(nil)
    }
  }
}
