name: starknet_paymaster
description: SNIP-29 compliant Paymaster SDK for Starknet Dart applications. Enables gasless transactions and flexible gas payments.
version: 0.1.0
homepage: https://github.com/avnu-labs/paymaster
repository: https://github.com/avnu-labs/paymaster

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.0
  mockito: ^5.4.2
  build_test: ^2.2.1

topics:
  - starknet
  - paymaster
  - blockchain
  - gasless
  - snip-29
