name: monorepo

packages:
  - examples/**
  - packages/**

ignore:
  - "examples/starknet_counter"
  - "packages/wallet_kit"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  validate-gh-actions:
    run: |
      action-validator .github/workflows/ci.yaml
  analyze:
    description: Analyze all packages
    exec: dart analyze --fatal-infos
  format:
    description: Format all packages
    exec: dart format .
  format:check:
    description: Format check all packages
    exec: dart format --set-exit-if-changed .

  starknet:setup:
    description: Install starknet dev env
    run: |
      asdf plugin add starknet-devnet https://github.com/ptisserand/asdf-starknet-devnet.git
      asdf install starknet-devnet $STARKNET_DEVNET_VERSION
      asdf local starknet-devnet $STARKNET_DEVNET_VERSION

      asdf plugin add scarb
      asdf install scarb $SCARB_VERSION
      asdf local scarb $SCARB_VERSION

      asdf plugin add starkli https://github.com/ptisserand/asdf-starkli.git
      asdf install starkli $STARKLI_VERSION
      asdf local starkli $STARKLI_VERSION

      asdf plugin add action-validator
      asdf install action-validator latest

      melos versions

  versions:
    description: Display toolchain versions
    run: |
      echo "starkli: $(starkli --version)"
      scarb --version
      starknet-devnet --version

  devnet:start:
    description: Start local devnet
    run: |
      starknet-devnet --seed 0 --dump-path $DEVNET_DUMP_PATH
  devnet:start-dump:
    description: Start local devnet in dump mode
    run: |
      rm ./assets/devnet-dump.json
      starknet-devnet --seed 0 --dump-path $DEVNET_DUMP_PATH --dump-on exit
  devnet:setup:
    description: Setup local devnet
    run: |
      melos contracts:build
      melos contracts:declare
      melos contracts:deploy

  contracts:build:
    description: Build cairo contracts
    run: |
      cd contracts/v$CAIRO_VERSION
      scarb build
  contracts:declare:
    description: Declare cairo contracts
    run: |
      starkli declare contracts/v$CAIRO_VERSION/target/dev/starknet_dart_hello.contract_class.json --compiler-version $CAIRO_VERSION
  contracts:deploy:
    description: Deploy cairo contracts
    run: |
      starkli deploy $HELLO_CLASS_HASH --salt $SALT 0x0
  hello:get_name:
    description: Call hello get_name
    run: |
      starkli call $HELLO_CONTRACT_ADDRESS get_name

  test:
    description: Run all tests
    steps:
      - melos test:dart:unit
      - melos test:dart:integration
  test:dart:unit:
    description: Run all dart unit tests
    run: melos exec --dir-exists="test" -- dart test --tags unit --fail-fast
    packageFilters:
      ignore: "*starknet_builder*"
      flutter: false
  test:dart:integration:
    description: Run all dart integration tests
    run: melos exec --dir-exists="test" -- dart test --tags integration --fail-fast
    packageFilters:
      ignore: "*starknet_builder*"
      flutter: false

  publish:dry-run:
    description: Publish dry-run all packages
    exec: dart pub publish --dry-run
    packageFilters:
      noPrivate: true

  upgrade:dart:
    name: Upgrade Dart package deps
    exec: dart pub upgrade
    packageFilters:
      flutter: false
  upgrade:flutter:
    name: Upgrade Flutter package deps
    exec: flutter pub upgrade
    packageFilters:
      flutter: true
