name: ark_project
description: Ark SDK for Dart and Flutter apps.
version: 0.1.0
repository: https://github.com/focustree/starknet.dart

environment:
  sdk: ">=3.0.0 <4.0.0" # Dart version constraint

dependencies:
  starknet:
  starknet_provider:
  http: ^1.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  dotenv: ^4.2.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
