name: ark_project
description: Ark SDK for Dart and Flutter apps.
version: 0.3.0
repository: https://github.com/focustree/starknet.dart

environment:
  sdk: ">=3.0.0 <4.0.0" # Dart version constraint

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  starknet: ^0.1.2+1
  starknet_provider: ^0.1.1+2

dev_dependencies:
  build_runner: ^2.4.13
  dotenv: ^4.2.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.25.8
