name: avnu_provider
description: Avnu provider for Dart and Flutter applications.
version: 0.0.2
repository: https://github.com/focustree/starknet.dart

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  starknet: ^0.1.2+1
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  json_annotation: ^4.9.0
  pointycastle: ^3.9.1
  starknet_provider: ^0.1.2+1

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.25.15