name: Build android examples

on:
  workflow_dispatch:

jobs:
  build-wallet-app-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Flutter setup
        uses: ./.github/actions/flutter-setup
      - name: Java/Android setup
        uses: ./.github/actions/android-setup
      - uses: bluefireteam/melos-action@v3
      - name: Build wallet_app example
        run: flutter build appbundle
        working-directory: ./examples/wallet_app
      - name: Build starknet_counter example
        run: flutter build appbundle
        working-directory: ./examples/starknet_counter
