name: Prepare release
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Version as prerelease"
        required: false
        default: false
        type: boolean

jobs:
  prepare-release:
    name: Prepare release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dotenv Action
        id: load-env
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env.ci
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.load-env.outputs.flutter_version }}
      - uses: bluefireteam/melos-action@v3
        with:
          run-versioning: ${{ inputs.prerelease == false }}
          run-versioning-prerelease: ${{ inputs.prerelease == true }}
          publish-dry-run: true
          create-pr: true
