name: Publish packages
on:
  workflow_dispatch:

jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Flutter setup
        uses: ./.github/actions/flutter-setup
      - uses: bluefireteam/melos-action@v3
        with:
          publish: true
