name: Tag release
on:
  push:
    branches: [main]

jobs:
  publish-packages:
    name: Create tags for release
    permissions:
      actions: write
      contents: write
    runs-on: [ubuntu-latest]
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dotenv Action
        id: load-env
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env.ci
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.load-env.outputs.flutter_version }}
      - uses: bluefireteam/melos-action@v3
        with:
          tag: true
      - run: |
          melos exec -c1 --no-published --no-private --order-dependents -- \
          gh workflow run release-publish.yaml \
          --ref \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
